export const workflowSteps = [
  "Anagrafica",
  "Investimenti",
  "Finanziamenti",
  "Personale",
  "Costi variabili",
  "Ricavi",
  "Break even",
  "Scenari",
  "Cash flow",
  "Report PDF",
];

export const investmentCategories = [
  "Cucina",
  "Sala",
  "Arredi",
  "Marketing",
  "Impianti",
  "Software",
  "Consulenze",
  "Hardware",
  "Ristrutturazioni",
  "Capitale circolante",
];

export const purchaseCategories = [
  { name: "Food", presetPct: 26, vat: 10 },
  { name: "Beverage", presetPct: 8, vat: 22 },
  { name: "Packaging", presetPct: 3, vat: 22 },
  { name: "Consumabili", presetPct: 2, vat: 22 },
  { name: "Detergenza", presetPct: 1.4, vat: 22 },
  { name: "Piccole attrezzature", presetPct: 1.2, vat: 22 },
  { name: "Divise personale", presetPct: 0.8, vat: 22 },
  { name: "Lavanderia", presetPct: 1.1, vat: 22 },
  { name: "Materiale monouso", presetPct: 1.8, vat: 22 },
  { name: "Commissioni delivery", presetPct: 4.5, vat: 22 },
  { name: "Materie prime", presetPct: 22, vat: 10 },
  { name: "Cancelleria", presetPct: 0.4, vat: 22 },
  { name: "Manutenzioni", presetPct: 1.5, vat: 22 },
  { name: "Marketing operativo", presetPct: 2.5, vat: 22 },
];

export const variableCostPresets = [
  {
    name: "Energia",
    small: 1800,
    medium: 3200,
    large: 5600,
    vat: 22,
    hint: "Valore consigliato in base a cucina, ore di apertura e metratura.",
  },
  {
    name: "Gas",
    small: 650,
    medium: 1100,
    large: 1900,
    vat: 22,
    hint: "Sale se il menu richiede molte cotture lunghe.",
  },
  {
    name: "Acqua",
    small: 260,
    medium: 420,
    large: 720,
    vat: 10,
    hint: "Include lavaggio, cucina e servizi.",
  },
  {
    name: "TARI",
    small: 300,
    medium: 560,
    large: 980,
    vat: 0,
    hint: "Dipende da comune, superficie e categoria rifiuti.",
  },
  {
    name: "POS",
    small: 320,
    medium: 650,
    large: 1050,
    vat: 22,
    hint: "Stimato su commissioni transato carta.",
  },
  {
    name: "Software",
    small: 180,
    medium: 320,
    large: 620,
    vat: 22,
    hint: "Cassa, prenotazioni, delivery, contabilità.",
  },
];

export const staffPresets = [
  { role: "Chef", people: 1, monthlyCost: 4200 },
  { role: "Cuoco", people: 1, monthlyCost: 3100 },
  { role: "Aiuto cuoco", people: 1, monthlyCost: 2400 },
  { role: "Sala", people: 2, monthlyCost: 2300 },
  { role: "Runner", people: 1, monthlyCost: 1600 },
  { role: "Manager", people: 1, monthlyCost: 3600 },
];

export const defaultInvestments = [
  {
    category: "Cucina",
    description: "Cuoci pasta",
    quantity: 1,
    unitPrice: 3800,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Cucina 6 fuochi gas",
    quantity: 1,
    unitPrice: 7200,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Friggitrice due vasche",
    quantity: 1,
    unitPrice: 4200,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Confezionatrice sottovuoto",
    quantity: 1,
    unitPrice: 2600,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Impastatrice pizzeria",
    quantity: 1,
    unitPrice: 5200,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Planetaria 5 litri",
    quantity: 1,
    unitPrice: 950,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Taglia verdure robot",
    quantity: 1,
    unitPrice: 1850,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Kit 5 dischi per tagliaverdure",
    quantity: 1,
    unitPrice: 420,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Frigorifero 1 porta",
    quantity: 2,
    unitPrice: 2200,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Congelatore 1 porta",
    quantity: 1,
    unitPrice: 2400,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Forno professionale combinato",
    quantity: 1,
    unitPrice: 14500,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Supporto base forno",
    quantity: 1,
    unitPrice: 950,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Tavolo refrigerato 2 porte",
    quantity: 1,
    unitPrice: 3600,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Abbattitore 5 teglie",
    quantity: 1,
    unitPrice: 6200,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Bilancia 20 kg",
    quantity: 1,
    unitPrice: 280,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Tramoggia su ruote",
    quantity: 1,
    unitPrice: 520,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Porta rifiuti carrellato",
    quantity: 2,
    unitPrice: 260,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Lavastoviglie professionale",
    quantity: 1,
    unitPrice: 5800,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Lavello 1 vasca",
    quantity: 1,
    unitPrice: 850,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Rubinetto monoforo",
    quantity: 1,
    unitPrice: 180,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Banco pizzeria con sportelli refrigerati",
    quantity: 1,
    unitPrice: 5800,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Lavamani a parete",
    quantity: 1,
    unitPrice: 520,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Bilancia digitale 8 kg",
    quantity: 1,
    unitPrice: 160,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Contenitori acciaio tavolo pizzeria",
    quantity: 1,
    unitPrice: 650,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Kit teglie per tagliata e verdure grigliate",
    quantity: 1,
    unitPrice: 780,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Minuteria cucina: pentole, bacinelle, coltelli",
    quantity: 1,
    unitPrice: 4800,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Scaffali inox cucina e magazzino",
    quantity: 1,
    unitPrice: 3200,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Cappa aspirazione cucina",
    quantity: 1,
    unitPrice: 9500,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cucina",
    description: "Fabbricatore di ghiaccio",
    quantity: 1,
    unitPrice: 2800,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Attrezzature bar",
    description: "Banco bar refrigerato",
    quantity: 1,
    unitPrice: 5200,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Attrezzature bar",
    description: "Macchina caffe professionale",
    quantity: 1,
    unitPrice: 8500,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Attrezzature bar",
    description: "Macinacaffe",
    quantity: 1,
    unitPrice: 1500,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Attrezzature bar",
    description: "Lavabicchieri",
    quantity: 1,
    unitPrice: 2800,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Sedie sala",
    quantity: 60,
    unitPrice: 95,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Tavoli sala",
    quantity: 24,
    unitPrice: 240,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Mobilia da arredamento sala",
    quantity: 1,
    unitPrice: 12000,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Bancone acciaio inox imbrunito",
    quantity: 1,
    unitPrice: 9500,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Piatto piano",
    quantity: 120,
    unitPrice: 6,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Piatto fondo",
    quantity: 80,
    unitPrice: 7,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Piatto pizza",
    quantity: 90,
    unitPrice: 8,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Piatto dessert / antipasto",
    quantity: 90,
    unitPrice: 5,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Bicchieri acqua e vino",
    quantity: 160,
    unitPrice: 3,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Posate sala complete",
    quantity: 120,
    unitPrice: 4,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Arredi sala",
    description: "Tovagliette alluminio",
    quantity: 80,
    unitPrice: 7,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Opere e impianti",
    description: "Struttura per tenda esterna",
    quantity: 1,
    unitPrice: 8500,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Opere e impianti",
    description: "Tinteggiatura locale",
    quantity: 1,
    unitPrice: 6500,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Opere e impianti",
    description: "Elettricista e adeguamento impianto",
    quantity: 1,
    unitPrice: 12000,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Opere e impianti",
    description: "Idraulico e scarichi cucina",
    quantity: 1,
    unitPrice: 8500,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Opere e impianti",
    description: "Illuminazione sala e cucina",
    quantity: 1,
    unitPrice: 6200,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cassa / POS",
    description: "Sistema cassa e stampanti comande",
    quantity: 1,
    unitPrice: 4200,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cassa / POS",
    description: "Palmari comande",
    quantity: 4,
    unitPrice: 420,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Cassa / POS",
    description: "Linea internet e telefonica",
    quantity: 1,
    unitPrice: 650,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Software",
    description: "Logo e sito web",
    quantity: 1,
    unitPrice: 3800,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Software",
    description: "Gestionale ristorante setup",
    quantity: 1,
    unitPrice: 2200,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Software",
    description: "Menu digitale / QR code",
    quantity: 1,
    unitPrice: 900,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Insegne",
    description: "Insegna esterna",
    quantity: 1,
    unitPrice: 4500,
    vat: 22,
    amortizable: true,
    years: 5,
  },
  {
    category: "Insegne",
    description: "Zerbino con stampa logo",
    quantity: 1,
    unitPrice: 380,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Marketing",
    description: "Taglia pizza gadget",
    quantity: 100,
    unitPrice: 2,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Marketing",
    description: "Bigliettini da visita",
    quantity: 1,
    unitPrice: 180,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Marketing",
    description: "Flyers apertura",
    quantity: 1,
    unitPrice: 450,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Marketing",
    description: "Stampa digitale vetrine e materiali",
    quantity: 1,
    unitPrice: 900,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Marketing",
    description: "Campagna social apertura",
    quantity: 1,
    unitPrice: 2500,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Divise",
    description: "Polo sala",
    quantity: 8,
    unitPrice: 38,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Divise",
    description: "Polo pizzeria",
    quantity: 4,
    unitPrice: 38,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Divise",
    description: "Cappelli pizzeria",
    quantity: 6,
    unitPrice: 18,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Divise",
    description: "Kit cuoco",
    quantity: 4,
    unitPrice: 85,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Divise",
    description: "Grembiuli",
    quantity: 10,
    unitPrice: 24,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Consulenze",
    description: "Consulenza apertura e fattibilita",
    quantity: 1,
    unitPrice: 2500,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Consulenze",
    description: "Commercialista apertura",
    quantity: 1,
    unitPrice: 1800,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Consulenze",
    description: "HACCP e sicurezza lavoro",
    quantity: 1,
    unitPrice: 1300,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Consulenze",
    description: "Pratiche comunali e SUAP",
    quantity: 1,
    unitPrice: 2200,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Capitale circolante",
    description: "Capitale circolante: affitto, utenze e food",
    quantity: 1,
    unitPrice: 30000,
    vat: 0,
    amortizable: false,
    years: 5,
  },
  {
    category: "Capitale circolante",
    description: "Scorte iniziali food",
    quantity: 1,
    unitPrice: 9000,
    vat: 10,
    amortizable: false,
    years: 5,
  },
  {
    category: "Capitale circolante",
    description: "Scorte iniziali beverage",
    quantity: 1,
    unitPrice: 5000,
    vat: 22,
    amortizable: false,
    years: 5,
  },
  {
    category: "Capitale circolante",
    description: "Cassa minima operativa",
    quantity: 1,
    unitPrice: 18000,
    vat: 0,
    amortizable: false,
    years: 5,
  },
  {
    category: "Altro",
    description: "Deposito cauzionale affitto",
    quantity: 1,
    unitPrice: 15000,
    vat: 0,
    amortizable: false,
    years: 5,
  },
  {
    category: "Altro",
    description: "Imprevisti apertura",
    quantity: 1,
    unitPrice: 12000,
    vat: 0,
    amortizable: false,
    years: 5,
  }
];

export const prudentialBenchmark = {
  source: "demo realistico ristorante medio",
  openingDaysAnnual: 310,
  averageTicketsVatIncluded: { A: 37.4, B: 46.2, C: 55 },
  averageTicketsNet: { A: 34, B: 42, C: 50 },
  foodCostPct: 28,
  otherVariableCostsPct: 9,
  totalVariableCostsPct: 37,
  variableCostPerCover: 15.54,
  fixedCostsAnnual: 444000,
  personnelAnnual: 294000,
  equipmentNet: 257500,
  forecastRevenue: 1126944,
  idealRevenue: 1260000,
  idealCoversAnnual: 26832,
  idealCoversDaily: 86,
  breakEvenCustomers: { A: 20090, B: 16780, C: 14100 },
  breakEvenCustomersDaily: { A: 65, B: 54, C: 45 },
  serviceMix: [
    { lunchPct: 38, dinnerPct: 62 },
    { lunchPct: 42, dinnerPct: 58 },
    { lunchPct: 35, dinnerPct: 65 },
  ],
};

export const prudentialCostRows = [
  { category: "Personale", name: "Chef responsabile", kind: "Fisso", monthly: 5200, annual: 72800, note: "Costo azienda stimato su 14 mensilita." },
  { category: "Personale", name: "Cuoco", kind: "Fisso", monthly: 3600, annual: 50400, note: "Costo azienda stimato su 14 mensilita." },
  { category: "Personale", name: "Aiuto cuoco", kind: "Fisso", monthly: 2800, annual: 39200, note: "Costo azienda stimato su 14 mensilita." },
  { category: "Personale", name: "Responsabile sala", kind: "Fisso", monthly: 3400, annual: 47600, note: "Costo azienda stimato su 14 mensilita." },
  { category: "Personale", name: "Camerieri sala", kind: "Fisso", monthly: 6200, annual: 86800, note: "Due risorse con oneri inclusi." },
  { category: "Personale", name: "Extra weekend e stagionali", kind: "Variabile", monthly: 4200, annual: 50400, note: "Personale flessibile per picchi e stagione estiva." },
  { category: "Materie prime", name: "Food", kind: "Variabile", monthly: 26250, annual: 315000, note: "Circa 28% del fatturato realistico." },
  { category: "Materie prime", name: "Beverage", kind: "Variabile", monthly: 7400, annual: 88800, note: "Incidenza media bevande e bar." },
  { category: "Locale", name: "Canone affitto", kind: "Fisso", monthly: 7200, annual: 86400, note: "Affitto zona ad alta visibilita." },
  { category: "Utenze", name: "Energia elettrica", kind: "Variabile", monthly: 3900, annual: 46800, note: "Cucina, frigo, climatizzazione e sala." },
  { category: "Utenze", name: "Gas", kind: "Variabile", monthly: 1350, annual: 16200, note: "Cotture e acqua calda." },
  { category: "Utenze", name: "Acqua", kind: "Variabile", monthly: 520, annual: 6240, note: "Cucina, lavaggio e servizi." },
  { category: "Servizi", name: "Software, cassa e prenotazioni", kind: "Fisso", monthly: 620, annual: 7440, note: "Canoni digitali ordinari." },
  { category: "Servizi", name: "Pulizie e lavanderia", kind: "Variabile", monthly: 1800, annual: 21600, note: "Tovagliato, divise e pulizie extra." },
  { category: "Marketing", name: "Marketing operativo", kind: "Fisso", monthly: 1400, annual: 16800, note: "Campagne locali, social e foto menu." },
  { category: "Tributi", name: "TARI", kind: "Fisso", monthly: 350, annual: 4200, note: "Stima comunale annua." },
  { category: "Licenze", name: "SIAE e autorizzazioni", kind: "Fisso", monthly: 120, annual: 1440, note: "Musica e autorizzazioni ricorrenti." },
  { category: "Consulenze", name: "Commercialista e paghe", kind: "Fisso", monthly: 720, annual: 8640, note: "Contabilita, paghe e adempimenti." },
  { category: "Manutenzioni", name: "Manutenzioni ordinarie", kind: "Fisso", monthly: 850, annual: 10200, note: "Attrezzature, impianti e piccole riparazioni." },
  { category: "Banca", name: "POS e spese bancarie", kind: "Variabile", monthly: 950, annual: 11400, note: "Commissioni su incassi elettronici." },
  { category: "Avvio", name: "Scorte iniziali", kind: "Una tantum", monthly: 0, annual: 18000, note: "Prima fornitura food, beverage e consumabili." },
  { category: "Avvio", name: "Liquidità di sicurezza", kind: "Una tantum", monthly: 0, annual: 30000, note: "Cassa prudenziale per i primi mesi." },
];
